# Generated by Django 3.1 on 2020-08-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'managed': True},
        ),
    ]
