# Generated by Django 3.1 on 2020-08-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
