# Generated by Django 3.1 on 2020-08-30 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_delete_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address_line', models.CharField(max_length=64)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('working_hours', models.CharField(blank=True, max_length=64)),
                ('person', models.CharField(blank=True, max_length=64)),
                ('details', models.TextField(blank=True)),
                ('social_media', models.URLField(blank=True)),
                ('active', models.BooleanField()),
                ('checked', models.BooleanField(default=False)),
                ('correct', models.BooleanField(default=False)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.state')),
                ('suburb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.suburb')),
            ],
            options={
                'db_table': 'schools',
                'managed': True,
            },
        ),
    ]
