# Generated by Django 3.1 on 2020-08-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20200817_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.state'),
        ),
        migrations.AddField(
            model_name='school',
            name='suburb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.suburb'),
        ),
    ]
