# Generated by Django 3.1 on 2020-08-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='person',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
