# Generated by Django 3.1 on 2020-08-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20200817_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='google_map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
