# Generated by Django 3.1 on 2020-08-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20200830_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='school',
            name='correct',
        ),
    ]
