# Generated by Django 3.1 on 2020-08-15 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('postcode', models.CharField(max_length=4)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.state')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address_line', models.CharField(max_length=64)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('working_hours', models.CharField(blank=True, max_length=64)),
                ('person', models.CharField(blank=True, max_length=64)),
                ('details', models.TextField(blank=True)),
                ('social_media', models.URLField(blank=True)),
                ('active', models.BooleanField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.state')),
                ('suburb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.suburb')),
            ],
        ),
    ]
