# Generated by Django 3.1 on 2020-08-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address_line', models.CharField(max_length=64)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('working_hours', models.CharField(blank=True, max_length=64)),
                ('person', models.CharField(blank=True, max_length=64)),
                ('details', models.TextField(blank=True)),
                ('social_media', models.URLField(blank=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'schools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suburbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('postcode', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'suburbs',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='suburb',
            name='state',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Suburb',
        ),
    ]
