# Generated by Django 3.1 on 2020-08-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20200817_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='google_map_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
