# Generated by Django 3.1 on 2020-08-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20200818_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
